# Generated by Django 3.1.5 on 2021-03-29 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('masterdata', '0006_auto_20210325_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderSalesProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('M', 'Main body'), ('F', 'Frame'), ('C', 'Cell'), ('N', 'Nail sheet')], max_length=1)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.product')),
            ],
        ),
        migrations.CreateModel(
            name='TraderSalesDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.document')),
            ],
        ),
        migrations.CreateModel(
            name='TraderSalesContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=200)),
                ('manager', models.CharField(blank=True, max_length=200, null=True)),
                ('person_in_charge', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('shipping_method', models.CharField(choices=[('D', 'Delivery'), ('R', 'Receipt'), ('C', 'ID Change'), ('B', '* Blank')], max_length=1)),
                ('shipping_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('TR', 'Transfer'), ('CH', 'Check'), ('BL', 'Bill'), ('CA', 'Cash')], max_length=2)),
                ('payment_due_date', models.DateField()),
                ('insurance_fee', models.IntegerField()),
                ('updated_at', models.DateField()),
                ('created_at', models.DateField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trader_sales_contracts', to='masterdata.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Product'), ('D', 'Document')], max_length=1)),
                ('expected_arrival_date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders', to='contracts.tradersalescontract')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.receiver')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Product'), ('D', 'Document')], max_length=1)),
                ('desired_arrival_date', models.DateField()),
                ('shipping_company', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.receiver')),
            ],
        ),
    ]
