# Generated by Django 3.1.5 on 2021-03-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_auto_20210325_1149'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TraderSalesDocument',
            new_name='ContractDocument',
        ),
        migrations.RenameModel(
            old_name='TraderSalesProduct',
            new_name='ContractProduct',
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='HallSalesContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('insurance_fee_included', models.BooleanField(default=True)),
                ('insurance_fee', models.IntegerField()),
                ('shipping_date', models.DateField()),
                ('opening_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('TR', 'Transfer'), ('CH', 'Check'), ('BL', 'Bill'), ('CA', 'Cash')], max_length=2)),
                ('transfer_account', models.CharField(max_length=255)),
                ('person_in_charge', models.CharField(max_length=200)),
                ('confirmor', models.CharField(max_length=200)),
                ('created_at', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_sales_contracts', to='masterdata.customer')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_sales_contracts', to='masterdata.hall')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDocumentFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Pachinko'), ('S', 'Slot')], max_length=1)),
                ('number_of_models', models.IntegerField()),
                ('number_of_units', models.IntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
