# Generated by Django 3.1.5 on 2021-02-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='shipping_method',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Picking up', 'Picking up'), ('ID change', 'ID change'), ('* Blank', '* Blank')], max_length=200, null=True),
        ),
    ]
