# Generated by Django 3.1.5 on 2021-03-30 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20210329_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallsalescontract',
            old_name='insurance_fee_included',
            new_name='insurance_fee_include',
        ),
        migrations.RenameField(
            model_name='milestone',
            old_name='payment_date',
            new_name='date',
        ),
    ]
