# Generated by Django 3.1.5 on 2021-03-30 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_auto_20210325_1149'),
        ('contracts', '0003_auto_20210330_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallsalescontract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.customer'),
        ),
        migrations.AlterField(
            model_name='hallsalescontract',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.hall'),
        ),
        migrations.AlterField(
            model_name='tradersalescontract',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.customer'),
        ),
        migrations.CreateModel(
            name='TraderPurchasesContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=200)),
                ('manager', models.CharField(blank=True, max_length=200, null=True)),
                ('person_in_charge', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('shipping_method', models.CharField(choices=[('D', 'Delivery'), ('R', 'Receipt'), ('C', 'ID Change'), ('B', '* Blank')], max_length=1)),
                ('shipping_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('TR', 'Transfer'), ('CH', 'Check'), ('BL', 'Bill'), ('CA', 'Cash')], max_length=2)),
                ('payment_due_date', models.DateField()),
                ('insurance_fee', models.IntegerField()),
                ('updated_at', models.DateField()),
                ('created_at', models.DateField()),
                ('transfer_deadline', models.DateField()),
                ('bank_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('account_holder', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HallPurchasesContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('insurance_fee_include', models.BooleanField(default=True)),
                ('insurance_fee', models.IntegerField()),
                ('shipping_date', models.DateField()),
                ('opening_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('TR', 'Transfer'), ('CH', 'Check'), ('BL', 'Bill'), ('CA', 'Cash')], max_length=2)),
                ('transfer_account', models.CharField(max_length=255)),
                ('person_in_charge', models.CharField(max_length=200)),
                ('confirmor', models.CharField(max_length=200)),
                ('created_at', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.customer')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.hall')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
