# Generated by Django 3.1.5 on 2021-03-30 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_documentfee'),
        ('contracts', '0004_auto_20210330_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractdocumentfee',
            name='type',
        ),
        migrations.AddField(
            model_name='contractdocumentfee',
            name='document_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.documentfee'),
        ),
    ]
