# Generated by Django 3.1.5 on 2021-02-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_hall_product_productorder_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='tax_classification',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
