# Generated by Django 3.1.5 on 2021-03-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='other',
            old_name='tax_classification',
            new_name='taxation',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='classification',
            new_name='type',
        ),
    ]
