# Generated by Django 3.1.5 on 2021-03-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20210319_0358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Other',
            new_name='OtherProduct',
        ),
    ]
