# Generated by Django 3.1.5 on 2021-03-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20210322_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='other',
            old_name='account',
            new_name='term',
        ),
    ]
