# Generated by Django 3.1.5 on 2021-03-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_auto_20210322_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='created_at',
        ),
    ]
