# Generated by Django 3.1.5 on 2021-03-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20210322_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
