# Generated by Django 3.1.5 on 2021-03-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_auto_20210322_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Other',
            new_name='Document',
        ),
    ]
