# Generated by Django 3.1.5 on 2021-03-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_auto_20210325_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Pachinko'), ('S', 'Slot')], max_length=1)),
                ('model_price', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('application_fee', models.IntegerField(default=30000)),
            ],
        ),
    ]
