# Generated by Django 3.1.5 on 2021-03-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_documentfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfee',
            name='application_fee',
        ),
    ]
