# Generated by Django 3.1.5 on 2021-03-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_remove_documentfee_application_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfee',
            name='application_fee',
            field=models.IntegerField(default=30000),
        ),
    ]
